### PR TITLE
Remove gh-pages deploy action

### PR DESCRIPTION
**Pull request by Dr-Electron**
# Description of change

I removed the GitHub action to stop the documentation deployment as we now have the wiki as single point of knowledge and should keep the old sites running.

Also your docs are a little different from the rest of the docs as you also add the Rust docs in it. 
So we need to decide how to handle that too

Now there are multiple solutions how this could work in the future:
- Merge this PR (After the decision for the Rust docs). PRs for the docs will still be tested by the action
- Remove the complete page. That will also disable the test of PRs
- Add the wiki-cli like identity did. That way you could clean up the documentation folder and use the wiki-cli for testing.
Check their folder content here: https://github.com/iotaledger/identity.rs/tree/dev/documentation

I will keep this PR a draft until you tell me how you want to proceed and I will implement it that way on this PR.

TO-DOs:
- [ ] Decide how to proceed
- [ ] Decide on how to handle Rust docs
- [ ] Don't forget to disable GH pages

## Type of change

- Documentation Fix

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by felsweg-iota** [comment]
Hello @Dr-Electron  thanks for contributing! Indeed, the most recent documentation concerning stronghold should reside inside the [wiki](https://wiki.iota.org). The Rust API docs will be seen on [docs.rs](https://docs.rs).

**Review by felsweg-iota — APPROVED** [review]
Yes, let's focus on the community wiki, and keep the API docs on docs.rs

**Comment by lucas-tortora** [comment]
@Dr-Electron , could you please review https://github.com/iotaledger/stronghold.rs/pull/266 ? If you think it's OK we can merge that and I'll replicate the changes in all the other docs.

**Comment by felsweg-iota** [comment]
Closed with [#266](https://github.com/iotaledger/stronghold.rs/pull/266)

**Pull request closed without merging**
