### PR TITLE
feature(cli) documentation by e2e testing

### PR DESCRIPTION
**Pull request by rootmos**
# Description of change

Improve documentation of the command line interface by running an end-to-end user journey.

Also note that this PR introduces the use of the `STRONGHOLD` environment variable to select a vault. Comments on the suitability of this name are welcome: should it be `STRONGHOLD_SNAPSHOT_DIR`, `VAULT`, other ideas?

## Type of change

Choose a type of change, and delete any options that are not relevant.

- [X] Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Running the `readme.sh` script uses the actual CLI to generate the `README.md`, nothing up my sleeves.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nothingismagick — APPROVED** [review]
I am ok with the `STRONGHOLD` env var name.

**Comment by nothingismagick** [comment]
The failing tests are not inside of the engine or the example.

**Comment by rootmos** [comment]
Are the compilation failures being looked into? @lucasfernog @mrbianchi tried to git blame, but couldn't find the exact culprit?

**Comment by rootmos** [comment]
@nothingismagick I remember you mentioning that the `readme.sh` script failed on your end, can you tell me the issue?

**Comment by nothingismagick** [comment]
Its something with BIP types. Will discuss with @mrbianchi later

**Comment by nothingismagick** [comment]
`readme.sh` no longer bails, so it must have been a heisenbug.

**Pull request merged**
