### PR TITLE
Add/update docs in stronghold

### PR DESCRIPTION
**Pull request by tensor-programming**
# Description of change

Add docs to all of the libraries apart from communications. 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] Enhancement (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by nothingismagick — APPROVED** [review]
Epic.

**Review by nothingismagick — CHANGES_REQUESTED** [review]
Since there are code changes (and readme's are changing) - this has an impact on the docs at crates.io and docs.rs, I think should at least get a minor point bump in every crate you have touched.

**Comment by tensor-programming** [comment]
> Since there are code changes (and readme's are changing) - this has an impact on the docs at crates.io and docs.rs, I think should at least get a minor point bump in every crate you have touched.

That would be client, engine, macro, runtime and Utils I believe.  So every single crate apart from the comms ones.  Will make the change.

**Comment by tensor-programming** [comment]
Should I add another retrospective or update the document?

**Review by nothingismagick — APPROVED** [review]

**Comment by nothingismagick** [comment]
I have to be honest, the addendum PR was probably the most moving code review I have ever had the privilege of approving. It was a pleasure working with you @tensor-programming and I think that many communities in the future will look back to this work and recognise that it came at a societal tipping point: A point in time where we collectively decided that security is no longer merely the privelege of the centralized; a place where we reclaimed the responsibility for our data, our secrets, and our identities. Indeed, the status quo of secret ownership has been fundamentally challenged, and as a maintainer of this code base I will actively support the acceptance and enhance the integration of Stronghold's philosophy. 

Thankyou

**Comment by tensor-programming** [comment]
It certainly was a journey taking this project from an idea to where it is now.  Its been a pleasure to work with all of the devs over at IOTA and especially you guys on the stronghold team.  I am continually surprised that even with my experience, I can keep evolving as a developer and it helps to be surrounded by passionate individuals.  I do believe stronghold will reach its potential with the current members working on it and I look forward to seeing how it changes as it moves towards the RC.

**Pull request merged**
