### PR TITLE
 Docs - Replace Import Strategy

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

* Replaced docusaurus-plugin-includes with remark-code-import abd remark-import-partial
* Upgraded Docusarus to improve mobile nav
* Fixed dependency warnings
* Replaced @include statements with @import

## Type of change

- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix

## How the change has been tested

Changes were tested on a locally mounted docs site.

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nothingismagick** [comment]
Thanks for the PR, but something is wrong that I can't debug :(

**Comment by lucas-tortora** [comment]
> Thanks for the PR, but something is wrong that I can't debug :(

What seems to be the problem? If you want we can schedule a quick call to try and work it out. Or if you have an error log please send it my way so I can review it :)

**Comment by nothingismagick** [comment]
https://github.com/iotaledger/stronghold.rs/pull/242/checks?check_run_id=3240181888

**Comment by lucas-tortora** [comment]
> https://github.com/iotaledger/stronghold.rs/pull/242/checks?check_run_id=3240181888

It seems webpack 5 doesn't work on this project. I've downgraded to 4 and things seems to work . 

https://github.com/iotaledger/stronghold.rs/pull/242/checks?check_run_id=3240904362

**Pull request merged**
