### PR TITLE
fix(snapshot): blake2b

### PR DESCRIPTION
**Pull request by nothingismagick**
# Description of change
This PR updates crypto.rs git revision and modifies the blake2b hashing approach to fit with upstream.

## Links to any relevant issues
https://github.com/iotaledger/crypto.rs/pull/52

## Type of change

Choose a type of change, and delete any options that are not relevant.
- [x] Enhancement (a non-breaking change which adds functionality)
Use the new `digest` approach.

## How the change has been tested
Tested locally on macOS - got some timeouts, am going to debug with CI.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nothingismagick** [comment]
@tensor-programming - I am not sure why I am still hitting a failure here in the test vectors:

```
failures:

---- logic::test::test_vectors stdout ----
Error: CryptoError(CipherError { alg: "xchacha20poly1305::decrypt" })
thread 'logic::test::test_vectors' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure'
 ```

**Comment by nothingismagick** [comment]
is it because of gustav's change to x25519 and the test vectors never got updated?

**Comment by tensor-programming** [comment]
> @tensor-programming - I am not sure why I am still hitting a failure here in the test vectors:
> 
> ```
> failures:
> 
> ---- logic::test::test_vectors stdout ----
> Error: CryptoError(CipherError { alg: "xchacha20poly1305::decrypt" })
> thread 'logic::test::test_vectors' panicked at 'assertion failed: `(left == right)`
>   left: `1`,
>  right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure'
> ```

Test vectors were broken somehow and the way that the conversion was happening for the nonce was just weirdly wrong.  Both have been corrected.

**Review by tensor-programming — APPROVED** [review]

**Comment by tensor-programming** [comment]
There's a clippy run under the format workflow which is very strange to me since clippy has its own workflow.  Might want to change that.  I fixed clippy by adding some `#[allow(clippy::unnecessary_wraps)]` tags which are temporary since some of this code will be removed shortly.

**Pull request merged**
